name: BuildAndTest

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  buildAndTest:
    runs-on: windows-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Build
        shell: cmd
        run: |
          @echo on
          build.cmd

      - name: Test
        shell: cmd
        run: |
          @echo on
          test.cmd